columns = ['account',
           'name',
           'Death',
           'archetype',
           'profession',
           'elite',
           'phases.All.actual_boss.dps',
           'phases.All.actual.dps',
           'phases.All.actual_boss.flanking',
           'phases.All.actual_boss.scholar',
           'phases.All.actual_boss.condi_dps',
           'phases.All.actual_boss.power_dps',
           'phases.All.buffs.aegis',
           'phases.All.buffs.alacrity',
           'phases.All.buffs.assassins_presence',
           'phases.All.buffs.banner_defence',
           'phases.All.buffs.banner_discipline',
           'phases.All.buffs.banner_strength',
           'phases.All.buffs.banner_tactics',
           'phases.All.buffs.empower_allies',
           'phases.All.buffs.fury',
           'phases.All.buffs.glyph_of_empowerment',
           'phases.All.buffs.lead_attacks',
           'phases.All.buffs.lotus_training',
           'phases.All.buffs.might',
           'phases.All.buffs.naturalistic_resonance',
           'phases.All.buffs.pinpoint_distribution',
           'phases.All.buffs.protection',
           'phases.All.buffs.quickness',
           'phases.All.buffs.regen',
           'phases.All.buffs.resist',
           'phases.All.buffs.retaliation',
           'phases.All.buffs.soothing_mist',
           'phases.All.buffs.spirit_of_frost',
           'phases.All.buffs.spotter',
           'phases.All.buffs.stab',
           'phases.All.buffs.stone_spirit',
           'phases.All.buffs.storm_spirit',
           'phases.All.buffs.sun_spirit',
           'phases.All.buffs.swift',
           'phases.All.buffs.vampiric_presence',
           'phases.All.buffs.vigor',
           'phases.All.buffs_out.aegis',
           'phases.All.buffs_out.alacrity',
           'phases.All.buffs_out.assassins_presence',
           'phases.All.buffs_out.banner_defence',
           'phases.All.buffs_out.banner_discipline',
           'phases.All.buffs_out.banner_strength',
           'phases.All.buffs_out.banner_tactics',
           'phases.All.buffs_out.empower_allies',
           'phases.All.buffs_out.fury',
           'phases.All.buffs_out.glyph_of_empowerment',
           'phases.All.buffs_out.lead_attacks',
           'phases.All.buffs_out.lotus_training',
           'phases.All.buffs_out.might',
           'phases.All.buffs_out.naturalistic_resonance',
           'phases.All.buffs_out.pinpoint_distribution',
           'phases.All.buffs_out.protection',
           'phases.All.buffs_out.quickness',
           'phases.All.buffs_out.regen',
           'phases.All.buffs_out.resist',
           'phases.All.buffs_out.retaliation',
           'phases.All.buffs_out.soothing_mist',
           'phases.All.buffs_out.spirit_of_frost',
           'phases.All.buffs_out.spotter',
           'phases.All.buffs_out.stab',
           'phases.All.buffs_out.stone_spirit',
           'phases.All.buffs_out.storm_spirit',
           'phases.All.buffs_out.sun_spirit',
           'phases.All.buffs_out.swift',
           'phases.All.buffs_out.vampiric_presence',
           'phases.All.buffs_out.vigor',
           'phases.All.events.dead_time',
           'phases.All.events.deaths',
           'phases.All.events.disconnect_time',
           'phases.All.events.disconnects',
           'phases.All.events.down_time',
           'phases.All.events.downs',
           'phases.All.received.dps',
           'phases.All.shielded.dps']

old_columns = ['account',
           'name',
           'Death',
           'archetype',
           'profession',
           'elite',
           'phases.All.actual_boss.dps',
           'phases.All.actual.dps',
           'phases.All.actual_boss.flanking',
           'phases.All.actual_boss.scholar',
           'phases.All.actual_boss.condi_dps',
           'phases.All.actual_boss.power_dps',
           'phases.All.buffs.alacrity',
           'phases.All.buffs.assassins_presence',
           'phases.All.buffs.banner_defence',
           'phases.All.buffs.banner_discipline',
           'phases.All.buffs.banner_strength',
           'phases.All.buffs.banner_tactics',
           'phases.All.buffs.empower_allies',
           'phases.All.buffs.fury',
           'phases.All.buffs.glyph_of_empowerment',
           'phases.All.buffs.gotl',
           'phases.All.buffs.lead_attacks',
           'phases.All.buffs.lotus_training',
           'phases.All.buffs.might',
           'phases.All.buffs.naturalistic_resonance',
           'phases.All.buffs.pinpoint_distribution',
           'phases.All.buffs.protection',
           'phases.All.buffs.quickness',
           'phases.All.buffs.soothing_mist',
           'phases.All.buffs.spirit_of_frost',
           'phases.All.buffs.spotter',
           'phases.All.buffs.stone_spirit',
           'phases.All.buffs.storm_spirit',
           'phases.All.buffs.sun_spirit',
           'phases.All.buffs.vampiric_presence',
           'phases.All.buffs_out.alacrity',
           'phases.All.buffs_out.assassins_presence',
           'phases.All.buffs_out.banner_defence',
           'phases.All.buffs_out.banner_discipline',
           'phases.All.buffs_out.banner_strength',
           'phases.All.buffs_out.banner_tactics',
           'phases.All.buffs_out.empower_allies',
           'phases.All.buffs_out.fury',
           'phases.All.buffs_out.glyph_of_empowerment',
           'phases.All.buffs_out.gotl',
           'phases.All.buffs_out.lead_attacks',
           'phases.All.buffs_out.lotus_training',
           'phases.All.buffs_out.might',
           'phases.All.buffs_out.naturalistic_resonance',
           'phases.All.buffs_out.pinpoint_distribution',
           'phases.All.buffs_out.protection',
           'phases.All.buffs_out.quickness',
           'phases.All.buffs_out.retaliation',
           'phases.All.buffs_out.soothing_mist',
           'phases.All.buffs_out.spirit_of_frost',
           'phases.All.buffs_out.spotter',
           'phases.All.buffs_out.stone_spirit',
           'phases.All.buffs_out.storm_spirit',
           'phases.All.buffs_out.sun_spirit',
           'phases.All.buffs_out.vampiric_presence',
           'phases.All.events.dead_time',
           'phases.All.events.deaths',
           'phases.All.events.disconnect_time',
           'phases.All.events.disconnects',
           'phases.All.events.down_time',
           'phases.All.events.downs',
           'phases.All.received.dps',
           'phases.All.shielded.dps']

vg_mechanics = ['phases.All.mechanics.Bullets Eaten',
                'phases.All.mechanics.Teleports']

gors_mechanics = ['phases.All.mechanics.Ghastly Imprisonments',
                  'phases.All.mechanics.Spectral Darkness',
                  'phases.All.mechanics.Unmitigated Spectral Impacts']

sab_mechanics = []

sloth_mechanics = ['phases.All.mechanics.Spores Blocked',
                   'phases.All.mechanics.Spores Received',
                   'phases.All.mechanics.Tantrum Knockdowns',
                   'phases.All.mechanics.Toxic Cloud Breathed',
                   'phases.All.mechanics.Volatile Poison Carrier']

matt_mechanics = ['phases.All.mechanics.Burning Stacks Received',
                 'phases.All.mechanics.Corrupted',
                 'phases.All.mechanics.Moved While Unbalanced',
                 'phases.All.mechanics.Sacrificed',
                 'phases.All.mechanics.Shards Absorbed',
                 'phases.All.mechanics.Surrender',
                 'phases.All.mechanics.Well of the Profane Carrier']

kc_mechanics = ['phases.All.mechanics.Correct Orb',
                'phases.All.mechanics.Wrong Orb']

xera_mechanics = ['phases.All.mechanics.Derangement']

cairn_mechanics = ['phases.All.mechanics.Displacement',
                    'phases.All.mechanics.Meteor Swarm',
                    'phases.All.mechanics.Shared Agony',
                    'phases.All.mechanics.Spatial Manipulation']

mo_mechanics = ['phases.All.mechanics.Claim',
                'phases.All.mechanics.Dispel',
                'phases.All.mechanics.Enemy Tile',
                'phases.All.mechanics.Protect',
                "phases.All.mechanics.Soldier's Aura"]

sam_mechanics = ['phases.All.mechanics.Anguished Bolt',
                    'phases.All.mechanics.Big Friend',
                    'phases.All.mechanics.Bludgeon',
                    'phases.All.mechanics.Charge',
                    'phases.All.mechanics.Claw',
                    'phases.All.mechanics.Fixate',
                    'phases.All.mechanics.Inevitable Betrayl',
                    'phases.All.mechanics.Prisoner Sweep',
                    'phases.All.mechanics.Shockwave',
                    'phases.All.mechanics.Small Friend',
                    'phases.All.mechanics.Spear Impact']

deimos_mechanics = ['phases.All.mechanics.Annihilate',
                    'phases.All.mechanics.Demonic Shockwave',
                    'phases.All.mechanics.Mind Crush',
                    'phases.All.mechanics.Rapid Decay',
                    'phases.All.mechanics.Soul Feast',
                    'phases.All.mechanics.Tear Consumed',
                    'phases.All.mechanics.Teleports']

sh_mechanics = ['phases.All.mechanics.Inner Vortex',
                    'phases.All.mechanics.Necrosis Received',
                    'phases.All.mechanics.Outer Vortex',
                    'phases.All.mechanics.Quad Slash',
                    'phases.All.mechanics.Scythe Hits',
                    'phases.All.mechanics.Soul Rift']

dhuum_mechanics = ['phases.All.mechanics.Death Marked',
                    'phases.All.mechanics.Dhuum Gaze',
                    'phases.All.mechanics.Fissured',
                    'phases.All.mechanics.Messenger',
                    'phases.All.mechanics.Putrid Bomb',
                    'phases.All.mechanics.Shackle Hits',
                    'phases.All.mechanics.Snatched',
                    'phases.All.mechanics.Sucked']
